apiVersion: v1
kind: Service
metadata:
  name: nginx-loadbalancer-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: 'true'
    external-dns.alpha.kubernetes.io/hostname: brandenkim.sandbox.k.do.ws.sonos.com
spec:
  selector:
    app: nginx
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80